version: '3'
services:

    api_users:
        build:
            context: ./api_users
            dockerfile: Dockerfile
        command: python -u app.py
        ports:
            - "5000:5000"
        volumes:
            - ./api_users:/app
        links:
            - mongodb
            - tokendealer

    tokendealer:
        build:
            context: ./token_dealer
            dockerfile: Dockerfile
        command: python -u jwt.py
        volumes:
            - ./token_dealer:/app

    front:
        build:
            context: ./front
            dockerfile: Dockerfile
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - ./front:/app/
            - /app/node_modules
            
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: usersdb